from pathlib import Path
import re

DESKTOP='''<section class="coverage-rail" aria-label="BIRC media coverage"><div class="coverage-title"><i aria-hidden="true"></i><strong>Published across</strong><span>/ 80</span></div><div class="coverage-outlets"><a href="https://idtvindia.com/" target="_blank" rel="noopener" aria-label="View BIRC coverage from IDTV India"><img src="https://www.google.com/s2/favicons?domain=idtvindia.com&sz=64" alt=""><span>IDTV India</span></a><a href="https://agrospectrumindia.com/" target="_blank" rel="noopener" aria-label="View BIRC coverage from AgroSpectrum India"><img src="https://www.google.com/s2/favicons?domain=agrospectrumindia.com&sz=64" alt=""><span>AgroSpectrum India</span></a><a href="https://economictimes.indiatimes.com/news/economy/agriculture" target="_blank" rel="noopener" aria-label="View BIRC coverage from The Economic Times"><img src="https://www.google.com/s2/favicons?domain=economictimes.indiatimes.com&sz=64" alt=""><span>The Economic Times</span></a><a href="https://krishijagran.com/" target="_blank" rel="noopener" aria-label="View BIRC coverage from Krishi Jagran"><img src="https://www.google.com/s2/favicons?domain=krishijagran.com&sz=64" alt=""><span>Krishi Jagran</span></a><a href="https://www.theindiaprint.com/" target="_blank" rel="noopener" aria-label="View BIRC coverage from The India Print"><img src="https://www.google.com/s2/favicons?domain=theindiaprint.com&sz=64" alt=""><span>The India Print</span></a><a href="https://newsable.asianetnews.com/business/indias-rice-sector-gets-boost-as-birc-2025-inks-rs-30435-cr-deals-articleshow-5lvluis" target="_blank" rel="noopener" aria-label="View BIRC coverage from Asianet Newsable"><img src="https://www.google.com/s2/favicons?domain=newsable.asianetnews.com&sz=64" alt=""><span>Asianet Newsable</span></a><a href="https://awaazthevoice.in/" target="_blank" rel="noopener" aria-label="View BIRC coverage from Awaaz The Voice"><img src="https://www.google.com/s2/favicons?domain=awaazthevoice.in&sz=64" alt=""><span>Awaaz, The Voice</span></a><a href="https://www.chinimandi.com/" target="_blank" rel="noopener" aria-label="View BIRC coverage from ChiniMandi"><img src="https://www.google.com/s2/favicons?domain=chinimandi.com&sz=64" alt=""><span>ChiniMandi</span></a></div><a class="coverage-all" href="https://birc.in/#coverage" target="_blank" rel="noopener">See the coverage <span>↗</span></a></section>'''

MOBILE='''<section class="coverage-rail coverage-mobile" aria-label="BIRC media coverage"><div class="coverage-head"><div class="coverage-title"><i aria-hidden="true"></i><strong>Published across</strong><span>/ 80</span></div><a class="coverage-all" href="https://birc.in/#coverage" target="_blank" rel="noopener">See coverage <span>↗</span></a></div><div class="coverage-outlets"><a href="https://idtvindia.com/" target="_blank" rel="noopener"><img src="https://www.google.com/s2/favicons?domain=idtvindia.com&sz=64" alt=""><span>IDTV India</span></a><a href="https://agrospectrumindia.com/" target="_blank" rel="noopener"><img src="https://www.google.com/s2/favicons?domain=agrospectrumindia.com&sz=64" alt=""><span>AgroSpectrum India</span></a><a href="https://economictimes.indiatimes.com/news/economy/agriculture" target="_blank" rel="noopener"><img src="https://www.google.com/s2/favicons?domain=economictimes.indiatimes.com&sz=64" alt=""><span>The Economic Times</span></a><a href="https://krishijagran.com/" target="_blank" rel="noopener"><img src="https://www.google.com/s2/favicons?domain=krishijagran.com&sz=64" alt=""><span>Krishi Jagran</span></a><a href="https://www.theindiaprint.com/" target="_blank" rel="noopener"><img src="https://www.google.com/s2/favicons?domain=theindiaprint.com&sz=64" alt=""><span>The India Print</span></a><a href="https://newsable.asianetnews.com/business/indias-rice-sector-gets-boost-as-birc-2025-inks-rs-30435-cr-deals-articleshow-5lvluis" target="_blank" rel="noopener"><img src="https://www.google.com/s2/favicons?domain=newsable.asianetnews.com&sz=64" alt=""><span>Asianet Newsable</span></a><a href="https://awaazthevoice.in/" target="_blank" rel="noopener"><img src="https://www.google.com/s2/favicons?domain=awaazthevoice.in&sz=64" alt=""><span>Awaaz, The Voice</span></a><a href="https://www.chinimandi.com/" target="_blank" rel="noopener"><img src="https://www.google.com/s2/favicons?domain=chinimandi.com&sz=64" alt=""><span>ChiniMandi</span></a></div></section>'''

DESKTOP_CSS=r'''
.coverage-rail{height:62px;display:grid;grid-template-columns:auto minmax(0,1fr) auto;background:var(--linen);color:var(--ink);border-block:1px solid var(--ll);overflow:hidden}
.coverage-title{padding:0 26px;display:flex;align-items:center;gap:9px;border-right:1px solid var(--ll);white-space:nowrap}.coverage-title i{width:7px;height:7px;background:var(--gold);transform:rotate(45deg)}.coverage-title strong{font:600 10px Poppins,sans-serif;letter-spacing:.15em;text-transform:uppercase}.coverage-title span{color:var(--lm);font:600 10px Poppins,sans-serif;letter-spacing:.12em}
.coverage-outlets{min-width:0;display:flex;overflow:hidden}.coverage-outlets a{min-width:max-content;padding:0 20px;display:flex;align-items:center;gap:10px;border-right:1px solid var(--ll);color:var(--lm);transition:background .18s var(--e),color .18s var(--e)}.coverage-outlets a:hover{background:var(--linen-2);color:var(--ink)}.coverage-outlets img{width:22px;height:22px;object-fit:contain}.coverage-outlets span{font:500 11px Poppins,sans-serif;white-space:nowrap}
.coverage-all{padding:0 28px;display:flex;align-items:center;gap:10px;border-left:1px solid var(--ll);font:600 10px Poppins,sans-serif;letter-spacing:.12em;text-transform:uppercase;white-space:nowrap}.coverage-all span{color:var(--gold-deep);font-size:14px}.coverage-all:hover{background:var(--ink);color:var(--linen)}
@media(max-width:1320px){.coverage-outlets a{padding-inline:16px}.coverage-outlets a:nth-last-child(-n+2){display:none}.coverage-title{padding-inline:20px}.coverage-all{padding-inline:20px}}
'''
MOBILE_CSS=r'''
.coverage-mobile{background:var(--l);color:var(--j);border-block:1px solid var(--ll);overflow:hidden}.coverage-head{height:52px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--ll)}.coverage-title{padding:0 var(--p);display:flex;align-items:center;gap:7px;white-space:nowrap}.coverage-title i{width:6px;height:6px;background:var(--g);transform:rotate(45deg)}.coverage-title strong{font:600 8px Poppins,sans-serif;letter-spacing:.14em;text-transform:uppercase}.coverage-title span{color:var(--lm);font:600 8px Poppins,sans-serif}.coverage-all{height:100%;padding:0 16px;display:flex;align-items:center;gap:7px;border-left:1px solid var(--ll);font:600 8px Poppins,sans-serif;letter-spacing:.1em;text-transform:uppercase}.coverage-all span{color:var(--g2)}.coverage-outlets{display:flex;overflow-x:auto;scroll-snap-type:x mandatory;scrollbar-width:none}.coverage-outlets::-webkit-scrollbar{display:none}.coverage-outlets a{min-width:156px;height:62px;padding:0 16px;display:flex;align-items:center;gap:10px;border-right:1px solid var(--ll);scroll-snap-align:start;color:var(--lm)}.coverage-outlets img{width:23px;height:23px;object-fit:contain}.coverage-outlets span{font:500 10px Poppins,sans-serif;white-space:nowrap}
'''

p=Path('desktop.html'); h=p.read_text()
h,n=re.subn(r'<div class="ticker".*?</div>\s*</div>',DESKTOP,h,count=1,flags=re.S);assert n==1
h=h.replace('</style>',DESKTOP_CSS+'</style>',1)
p.write_text(h)

p=Path('index.html'); h=p.read_text()
h,n=re.subn(r'<div class="ticker"><div>.*?</div></div>',MOBILE,h,count=1,flags=re.S);assert n==1
marker='</style><style id="view-switch-style">';assert marker in h
h=h.replace(marker,MOBILE_CSS+'</style><style id="view-switch-style">',1)
p.write_text(h)

p=Path('context.md'); text=p.read_text()
needle='- Gallery placeholders are intentionally 20% larger than the original gallery. Preserve.'
replacement='- The previous rotating facts ticker below the hero is replaced on desktop and mobile by a media coverage rail titled `Published across / 80`. It shows clickable publisher marks and ends with a `See the coverage` action; mobile uses horizontal scroll snapping.\n'+needle
assert needle in text
p.write_text(text.replace(needle,replacement,1))
